/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PerpetualV1Interface extends ethers.utils.Interface {
  functions: {
    "depositToPosition(address,uint256,bytes32)": FunctionFragment;
    "enableFinalSettlement(uint256,uint256)": FunctionFragment;
    "getAccountBalanceAfterSettlement(address)": FunctionFragment;
    "getAccountIndex(address)": FunctionFragment;
    "getAccountPositionBalance(address)": FunctionFragment;
    "getAdmin()": FunctionFragment;
    "getFeePoolContract()": FunctionFragment;
    "getFinalSettlementEnabled()": FunctionFragment;
    "getFunderContract()": FunctionFragment;
    "getGlobalIndex()": FunctionFragment;
    "getInitialMargin()": FunctionFragment;
    "getIsGlobalOperator(address)": FunctionFragment;
    "getIsLocalOperator(address,address)": FunctionFragment;
    "getMaintenanceMargin()": FunctionFragment;
    "getOracleContract()": FunctionFragment;
    "getOraclePrice()": FunctionFragment;
    "getTokenContract()": FunctionFragment;
    "getTradeInfoContract()": FunctionFragment;
    "getTradingStartTime()": FunctionFragment;
    "hasAccountPermissions(address,address)": FunctionFragment;
    "initializeV1(address,address,address,uint256,uint256,string)": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setFeePool(address)": FunctionFragment;
    "setFunder(address)": FunctionFragment;
    "setGlobalOperator(address,bool)": FunctionFragment;
    "setInitialMargin(uint256)": FunctionFragment;
    "setLocalOperator(address,bool)": FunctionFragment;
    "setMaintenanceMargin(uint256)": FunctionFragment;
    "setMarginBank(address)": FunctionFragment;
    "setOracle(address)": FunctionFragment;
    "setTradeInfo(address)": FunctionFragment;
    "startTrading()": FunctionFragment;
    "stopTrading()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "trade(address[],tuple[])": FunctionFragment;
    "transferFromPosition(address,address,uint256,bytes32)": FunctionFragment;
    "withdrawFinalSettlement()": FunctionFragment;
    "withdrawFromPosition(address,address,uint256,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositToPosition",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableFinalSettlement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountBalanceAfterSettlement",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountPositionBalance",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFeePoolContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalSettlementEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFunderContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInitialMargin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIsGlobalOperator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIsLocalOperator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaintenanceMargin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOraclePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeInfoContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccountPermissions",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV1",
    values: [string, string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "setAdmin", values: [string]): string;
  encodeFunctionData(functionFragment: "setFeePool", values: [string]): string;
  encodeFunctionData(functionFragment: "setFunder", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGlobalOperator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setInitialMargin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLocalOperator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaintenanceMargin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarginBank",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setOracle", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setTradeInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "startTrading",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopTrading",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trade",
    values: [
      string[],
      {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFromPosition",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFinalSettlement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromPosition",
    values: [string, string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositToPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableFinalSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountBalanceAfterSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountPositionBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeePoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalSettlementEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFunderContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInitialMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsGlobalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsLocalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaintenanceMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOraclePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeInfoContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAccountPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFunder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInitialMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLocalOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaintenanceMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarginBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTradeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFromPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFinalSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromPosition",
    data: BytesLike
  ): Result;

  events: {
    "LogAccountSettled(address,bool,bool,uint256,uint256,uint256,uint256,bytes32,string)": EventFragment;
    "LogFinalSettlementEnabled(uint256)": EventFragment;
    "LogIndex(bytes32)": EventFragment;
    "LogPositionBalanceDeposit(address,uint256,bytes32,uint256,bytes32,uint256)": EventFragment;
    "LogPositionBalanceWithdraw(address,address,uint256,bytes32,uint256,bytes32,uint256)": EventFragment;
    "LogSetFeePool(address)": EventFragment;
    "LogSetFunder(address)": EventFragment;
    "LogSetGlobalOperator(address,bool)": EventFragment;
    "LogSetInitialMargin(uint256)": EventFragment;
    "LogSetLocalOperator(address,address,bool)": EventFragment;
    "LogSetMaintenanceMargin(uint256)": EventFragment;
    "LogSetMarginBank(address)": EventFragment;
    "LogSetOracle(address)": EventFragment;
    "LogSetTradeInfo(address)": EventFragment;
    "LogTrade(address,address,address,bytes32,bool,bytes32,bytes32,bytes,uint256,uint256,bytes32,uint256)": EventFragment;
    "LogTradeDeposit(address,uint256,bytes32)": EventFragment;
    "LogTradeWithdraw(address,uint256,bytes32)": EventFragment;
    "LogTradingStarted(uint256)": EventFragment;
    "LogTradingStopped(uint256)": EventFragment;
    "LogWithdrawFinalSettlement(address,uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogAccountSettled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFinalSettlementEnabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogIndex"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogPositionBalanceDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogPositionBalanceWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetFeePool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetFunder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetGlobalOperator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetInitialMargin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetLocalOperator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetMaintenanceMargin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetMarginBank"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetOracle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSetTradeInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTrade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTradeDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTradeWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTradingStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTradingStopped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogWithdrawFinalSettlement"): EventFragment;
}

export class PerpetualV1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PerpetualV1Interface;

  functions: {
    depositToPosition(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "depositToPosition(address,uint256,bytes32)"(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableFinalSettlement(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "enableFinalSettlement(uint256,uint256)"(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAccountBalanceAfterSettlement(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          }
        ] & {
          price: BigNumber;
          maintenanceMargin: BigNumber;
          initialMargin: BigNumber;
          index: [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          };
        }
      ]
    >;

    "getAccountBalanceAfterSettlement(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          }
        ] & {
          price: BigNumber;
          maintenanceMargin: BigNumber;
          initialMargin: BigNumber;
          index: [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          };
        }
      ]
    >;

    getAccountIndex(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ]
    >;

    "getAccountIndex(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ]
    >;

    getAccountPositionBalance(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        }
      ]
    >;

    "getAccountPositionBalance(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        }
      ]
    >;

    getAdmin(overrides?: CallOverrides): Promise<[string]>;

    "getAdmin()"(overrides?: CallOverrides): Promise<[string]>;

    getFeePoolContract(overrides?: CallOverrides): Promise<[string]>;

    "getFeePoolContract()"(overrides?: CallOverrides): Promise<[string]>;

    getFinalSettlementEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    "getFinalSettlementEnabled()"(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getFunderContract(overrides?: CallOverrides): Promise<[string]>;

    "getFunderContract()"(overrides?: CallOverrides): Promise<[string]>;

    getGlobalIndex(
      overrides?: CallOverrides
    ): Promise<
      [
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ]
    >;

    "getGlobalIndex()"(
      overrides?: CallOverrides
    ): Promise<
      [
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ]
    >;

    getInitialMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getInitialMargin()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "getIsGlobalOperator(address)"(
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getIsLocalOperator(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "getIsLocalOperator(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getMaintenanceMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getMaintenanceMargin()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOracleContract(overrides?: CallOverrides): Promise<[string]>;

    "getOracleContract()"(overrides?: CallOverrides): Promise<[string]>;

    getOraclePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getOraclePrice()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTokenContract(overrides?: CallOverrides): Promise<[string]>;

    "getTokenContract()"(overrides?: CallOverrides): Promise<[string]>;

    getTradeInfoContract(overrides?: CallOverrides): Promise<[string]>;

    "getTradeInfoContract()"(overrides?: CallOverrides): Promise<[string]>;

    getTradingStartTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getTradingStartTime()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    hasAccountPermissions(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasAccountPermissions(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initializeV1(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initializeV1(address,address,address,uint256,uint256,string)"(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAdmin(address)"(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeePool(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setFeePool(address)"(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFunder(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setFunder(address)"(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setGlobalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInitialMargin(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setInitialMargin(uint256)"(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLocalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setLocalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaintenanceMargin(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMaintenanceMargin(uint256)"(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMarginBank(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMarginBank(address)"(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOracle(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setOracle(address)"(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTradeInfo(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTradeInfo(address)"(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "startTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "stopTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    trade(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "trade(address[],tuple[])"(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawFinalSettlement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawFinalSettlement()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositToPosition(
    account: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "depositToPosition(address,uint256,bytes32)"(
    account: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableFinalSettlement(
    priceLowerBound: BigNumberish,
    priceUpperBound: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "enableFinalSettlement(uint256,uint256)"(
    priceLowerBound: BigNumberish,
    priceUpperBound: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAccountBalanceAfterSettlement(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      },
      [
        BigNumber,
        BigNumber,
        BigNumber,
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ] & {
        price: BigNumber;
        maintenanceMargin: BigNumber;
        initialMargin: BigNumber;
        index: [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        };
      }
    ]
  >;

  "getAccountBalanceAfterSettlement(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      },
      [
        BigNumber,
        BigNumber,
        BigNumber,
        [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        }
      ] & {
        price: BigNumber;
        maintenanceMargin: BigNumber;
        initialMargin: BigNumber;
        index: [number, boolean, BigNumber] & {
          timestamp: number;
          isPositive: boolean;
          value: BigNumber;
        };
      }
    ]
  >;

  getAccountIndex(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [number, boolean, BigNumber] & {
      timestamp: number;
      isPositive: boolean;
      value: BigNumber;
    }
  >;

  "getAccountIndex(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [number, boolean, BigNumber] & {
      timestamp: number;
      isPositive: boolean;
      value: BigNumber;
    }
  >;

  getAccountPositionBalance(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
      debt: BigNumber;
      debtIsPositive: boolean;
      size: BigNumber;
      sizeIsPositive: boolean;
      margin: BigNumber;
    }
  >;

  "getAccountPositionBalance(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
      debt: BigNumber;
      debtIsPositive: boolean;
      size: BigNumber;
      sizeIsPositive: boolean;
      margin: BigNumber;
    }
  >;

  getAdmin(overrides?: CallOverrides): Promise<string>;

  "getAdmin()"(overrides?: CallOverrides): Promise<string>;

  getFeePoolContract(overrides?: CallOverrides): Promise<string>;

  "getFeePoolContract()"(overrides?: CallOverrides): Promise<string>;

  getFinalSettlementEnabled(overrides?: CallOverrides): Promise<boolean>;

  "getFinalSettlementEnabled()"(overrides?: CallOverrides): Promise<boolean>;

  getFunderContract(overrides?: CallOverrides): Promise<string>;

  "getFunderContract()"(overrides?: CallOverrides): Promise<string>;

  getGlobalIndex(
    overrides?: CallOverrides
  ): Promise<
    [number, boolean, BigNumber] & {
      timestamp: number;
      isPositive: boolean;
      value: BigNumber;
    }
  >;

  "getGlobalIndex()"(
    overrides?: CallOverrides
  ): Promise<
    [number, boolean, BigNumber] & {
      timestamp: number;
      isPositive: boolean;
      value: BigNumber;
    }
  >;

  getInitialMargin(overrides?: CallOverrides): Promise<BigNumber>;

  "getInitialMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

  getIsGlobalOperator(
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getIsGlobalOperator(address)"(
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getIsLocalOperator(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getIsLocalOperator(address,address)"(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getMaintenanceMargin(overrides?: CallOverrides): Promise<BigNumber>;

  "getMaintenanceMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

  getOracleContract(overrides?: CallOverrides): Promise<string>;

  "getOracleContract()"(overrides?: CallOverrides): Promise<string>;

  getOraclePrice(overrides?: CallOverrides): Promise<BigNumber>;

  "getOraclePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  getTokenContract(overrides?: CallOverrides): Promise<string>;

  "getTokenContract()"(overrides?: CallOverrides): Promise<string>;

  getTradeInfoContract(overrides?: CallOverrides): Promise<string>;

  "getTradeInfoContract()"(overrides?: CallOverrides): Promise<string>;

  getTradingStartTime(overrides?: CallOverrides): Promise<BigNumber>;

  "getTradingStartTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  hasAccountPermissions(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasAccountPermissions(address,address)"(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initializeV1(
    token: string,
    oracle: string,
    funder: string,
    maintenanceMargin: BigNumberish,
    initialMargin: BigNumberish,
    marketKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initializeV1(address,address,address,uint256,uint256,string)"(
    token: string,
    oracle: string,
    funder: string,
    maintenanceMargin: BigNumberish,
    initialMargin: BigNumberish,
    marketKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    admin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAdmin(address)"(
    admin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeePool(
    feePool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setFeePool(address)"(
    feePool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFunder(
    funder: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setFunder(address)"(
    funder: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGlobalOperator(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setGlobalOperator(address,bool)"(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInitialMargin(
    initialMargin: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setInitialMargin(uint256)"(
    initialMargin: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLocalOperator(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setLocalOperator(address,bool)"(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaintenanceMargin(
    maintenanceMargin: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMaintenanceMargin(uint256)"(
    maintenanceMargin: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMarginBank(
    marginBank: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMarginBank(address)"(
    marginBank: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOracle(
    oracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setOracle(address)"(
    oracle: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTradeInfo(
    tradeInfo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTradeInfo(address)"(
    tradeInfo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startTrading(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "startTrading()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopTrading(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "stopTrading()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  trade(
    accounts: string[],
    trades: {
      takerIndex: BigNumberish;
      makerIndex: BigNumberish;
      trader: string;
      data: BytesLike;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "trade(address[],tuple[])"(
    accounts: string[],
    trades: {
      takerIndex: BigNumberish;
      makerIndex: BigNumberish;
      trader: string;
      data: BytesLike;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFromPosition(
    account: string,
    destination: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferFromPosition(address,address,uint256,bytes32)"(
    account: string,
    destination: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawFinalSettlement(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawFinalSettlement()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawFromPosition(
    account: string,
    destination: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawFromPosition(address,address,uint256,bytes32)"(
    account: string,
    destination: string,
    amount: BigNumberish,
    memo: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositToPosition(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      }
    >;

    "depositToPosition(address,uint256,bytes32)"(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      }
    >;

    enableFinalSettlement(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "enableFinalSettlement(uint256,uint256)"(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAccountBalanceAfterSettlement(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          }
        ] & {
          price: BigNumber;
          maintenanceMargin: BigNumber;
          initialMargin: BigNumber;
          index: [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          };
        }
      ]
    >;

    "getAccountBalanceAfterSettlement(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
          debt: BigNumber;
          debtIsPositive: boolean;
          size: BigNumber;
          sizeIsPositive: boolean;
          margin: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          }
        ] & {
          price: BigNumber;
          maintenanceMargin: BigNumber;
          initialMargin: BigNumber;
          index: [number, boolean, BigNumber] & {
            timestamp: number;
            isPositive: boolean;
            value: BigNumber;
          };
        }
      ]
    >;

    getAccountIndex(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [number, boolean, BigNumber] & {
        timestamp: number;
        isPositive: boolean;
        value: BigNumber;
      }
    >;

    "getAccountIndex(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [number, boolean, BigNumber] & {
        timestamp: number;
        isPositive: boolean;
        value: BigNumber;
      }
    >;

    getAccountPositionBalance(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      }
    >;

    "getAccountPositionBalance(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean, BigNumber, boolean, BigNumber] & {
        debt: BigNumber;
        debtIsPositive: boolean;
        size: BigNumber;
        sizeIsPositive: boolean;
        margin: BigNumber;
      }
    >;

    getAdmin(overrides?: CallOverrides): Promise<string>;

    "getAdmin()"(overrides?: CallOverrides): Promise<string>;

    getFeePoolContract(overrides?: CallOverrides): Promise<string>;

    "getFeePoolContract()"(overrides?: CallOverrides): Promise<string>;

    getFinalSettlementEnabled(overrides?: CallOverrides): Promise<boolean>;

    "getFinalSettlementEnabled()"(overrides?: CallOverrides): Promise<boolean>;

    getFunderContract(overrides?: CallOverrides): Promise<string>;

    "getFunderContract()"(overrides?: CallOverrides): Promise<string>;

    getGlobalIndex(
      overrides?: CallOverrides
    ): Promise<
      [number, boolean, BigNumber] & {
        timestamp: number;
        isPositive: boolean;
        value: BigNumber;
      }
    >;

    "getGlobalIndex()"(
      overrides?: CallOverrides
    ): Promise<
      [number, boolean, BigNumber] & {
        timestamp: number;
        isPositive: boolean;
        value: BigNumber;
      }
    >;

    getInitialMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitialMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getIsGlobalOperator(address)"(
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getIsLocalOperator(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getIsLocalOperator(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getMaintenanceMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "getMaintenanceMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOracleContract(overrides?: CallOverrides): Promise<string>;

    "getOracleContract()"(overrides?: CallOverrides): Promise<string>;

    getOraclePrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getOraclePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenContract(overrides?: CallOverrides): Promise<string>;

    "getTokenContract()"(overrides?: CallOverrides): Promise<string>;

    getTradeInfoContract(overrides?: CallOverrides): Promise<string>;

    "getTradeInfoContract()"(overrides?: CallOverrides): Promise<string>;

    getTradingStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    "getTradingStartTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    hasAccountPermissions(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasAccountPermissions(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initializeV1(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initializeV1(address,address,address,uint256,uint256,string)"(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAdmin(admin: string, overrides?: CallOverrides): Promise<boolean>;

    "setAdmin(address)"(
      admin: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setFeePool(feePool: string, overrides?: CallOverrides): Promise<void>;

    "setFeePool(address)"(
      feePool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFunder(funder: string, overrides?: CallOverrides): Promise<void>;

    "setFunder(address)"(
      funder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGlobalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setInitialMargin(
      initialMargin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setInitialMargin(uint256)"(
      initialMargin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLocalOperator(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setLocalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaintenanceMargin(
      maintenanceMargin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMaintenanceMargin(uint256)"(
      maintenanceMargin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMarginBank(marginBank: string, overrides?: CallOverrides): Promise<void>;

    "setMarginBank(address)"(
      marginBank: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setOracle(oracle: string, overrides?: CallOverrides): Promise<void>;

    "setOracle(address)"(
      oracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTradeInfo(tradeInfo: string, overrides?: CallOverrides): Promise<void>;

    "setTradeInfo(address)"(
      tradeInfo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    startTrading(overrides?: CallOverrides): Promise<void>;

    "startTrading()"(overrides?: CallOverrides): Promise<void>;

    stopTrading(overrides?: CallOverrides): Promise<void>;

    "stopTrading()"(overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    trade(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "trade(address[],tuple[])"(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdrawFinalSettlement(overrides?: CallOverrides): Promise<void>;

    "withdrawFinalSettlement()"(overrides?: CallOverrides): Promise<void>;

    withdrawFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LogAccountSettled(
      account: string | null,
      isPositive: null,
      isFundingRatePositive: null,
      amount: null,
      fundingRate: null,
      price: null,
      timestamp: null,
      balance: null,
      symbol: null
    ): TypedEventFilter<
      [
        string,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        string
      ],
      {
        account: string;
        isPositive: boolean;
        isFundingRatePositive: boolean;
        amount: BigNumber;
        fundingRate: BigNumber;
        price: BigNumber;
        timestamp: BigNumber;
        balance: string;
        symbol: string;
      }
    >;

    LogFinalSettlementEnabled(
      settlementPrice: null
    ): TypedEventFilter<[BigNumber], { settlementPrice: BigNumber }>;

    LogIndex(index: null): TypedEventFilter<[string], { index: string }>;

    LogPositionBalanceDeposit(
      account: string | null,
      amount: null,
      balance: null,
      margin: null,
      memo: null,
      timestamp: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, string, BigNumber],
      {
        account: string;
        amount: BigNumber;
        balance: string;
        margin: BigNumber;
        memo: string;
        timestamp: BigNumber;
      }
    >;

    LogPositionBalanceWithdraw(
      account: string | null,
      destination: null,
      amount: null,
      balance: null,
      margin: null,
      memo: null,
      timestamp: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber, string, BigNumber],
      {
        account: string;
        destination: string;
        amount: BigNumber;
        balance: string;
        margin: BigNumber;
        memo: string;
        timestamp: BigNumber;
      }
    >;

    LogSetFeePool(
      feePool: null
    ): TypedEventFilter<[string], { feePool: string }>;

    LogSetFunder(funder: null): TypedEventFilter<[string], { funder: string }>;

    LogSetGlobalOperator(
      operator: null,
      approved: null
    ): TypedEventFilter<
      [string, boolean],
      { operator: string; approved: boolean }
    >;

    LogSetInitialMargin(
      initialMargin: null
    ): TypedEventFilter<[BigNumber], { initialMargin: BigNumber }>;

    LogSetLocalOperator(
      sender: string | null,
      operator: null,
      approved: null
    ): TypedEventFilter<
      [string, string, boolean],
      { sender: string; operator: string; approved: boolean }
    >;

    LogSetMaintenanceMargin(
      maintenanceMargin: null
    ): TypedEventFilter<[BigNumber], { maintenanceMargin: BigNumber }>;

    LogSetMarginBank(
      marginBank: null
    ): TypedEventFilter<[string], { marginBank: string }>;

    LogSetOracle(oracle: null): TypedEventFilter<[string], { oracle: string }>;

    LogSetTradeInfo(
      tradeInfo: null
    ): TypedEventFilter<[string], { tradeInfo: string }>;

    LogTrade(
      maker: null,
      taker: null,
      trader: null,
      debtAndSize: null,
      isBuy: null,
      makerBalance: null,
      takerBalance: null,
      data: null,
      makerPositionMargin: null,
      takerPositionMargin: null,
      fee: null,
      timestamp: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        boolean,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ],
      {
        maker: string;
        taker: string;
        trader: string;
        debtAndSize: string;
        isBuy: boolean;
        makerBalance: string;
        takerBalance: string;
        data: string;
        makerPositionMargin: BigNumber;
        takerPositionMargin: BigNumber;
        fee: string;
        timestamp: BigNumber;
      }
    >;

    LogTradeDeposit(
      account: string | null,
      amount: null,
      balance: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { account: string; amount: BigNumber; balance: string }
    >;

    LogTradeWithdraw(
      account: string | null,
      amount: null,
      balance: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { account: string; amount: BigNumber; balance: string }
    >;

    LogTradingStarted(
      startTime: null
    ): TypedEventFilter<[BigNumber], { startTime: BigNumber }>;

    LogTradingStopped(
      stopTime: null
    ): TypedEventFilter<[BigNumber], { stopTime: BigNumber }>;

    LogWithdrawFinalSettlement(
      account: string | null,
      amount: null,
      balance: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { account: string; amount: BigNumber; balance: string }
    >;
  };

  estimateGas: {
    depositToPosition(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "depositToPosition(address,uint256,bytes32)"(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableFinalSettlement(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "enableFinalSettlement(uint256,uint256)"(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAccountBalanceAfterSettlement(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAccountBalanceAfterSettlement(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountIndex(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAccountIndex(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAccountPositionBalance(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAccountPositionBalance(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    "getAdmin()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFeePoolContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getFeePoolContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFinalSettlementEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    "getFinalSettlementEnabled()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFunderContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getFunderContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getGlobalIndex(overrides?: CallOverrides): Promise<BigNumber>;

    "getGlobalIndex()"(overrides?: CallOverrides): Promise<BigNumber>;

    getInitialMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "getInitialMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIsGlobalOperator(address)"(
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIsLocalOperator(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getIsLocalOperator(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaintenanceMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "getMaintenanceMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOracleContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getOracleContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOraclePrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getOraclePrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getTokenContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTradeInfoContract(overrides?: CallOverrides): Promise<BigNumber>;

    "getTradeInfoContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTradingStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    "getTradingStartTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    hasAccountPermissions(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasAccountPermissions(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeV1(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initializeV1(address,address,address,uint256,uint256,string)"(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAdmin(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAdmin(address)"(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeePool(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setFeePool(address)"(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFunder(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setFunder(address)"(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setGlobalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInitialMargin(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setInitialMargin(uint256)"(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLocalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setLocalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaintenanceMargin(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMaintenanceMargin(uint256)"(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMarginBank(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMarginBank(address)"(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOracle(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setOracle(address)"(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTradeInfo(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTradeInfo(address)"(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "startTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "stopTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    trade(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "trade(address[],tuple[])"(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawFinalSettlement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawFinalSettlement()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositToPosition(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "depositToPosition(address,uint256,bytes32)"(
      account: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableFinalSettlement(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "enableFinalSettlement(uint256,uint256)"(
      priceLowerBound: BigNumberish,
      priceUpperBound: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAccountBalanceAfterSettlement(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAccountBalanceAfterSettlement(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountIndex(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAccountIndex(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAccountPositionBalance(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAccountPositionBalance(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAdmin()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeePoolContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFeePoolContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFinalSettlementEnabled(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFinalSettlementEnabled()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFunderContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getFunderContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGlobalIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getGlobalIndex()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInitialMargin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getInitialMargin()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsGlobalOperator(
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getIsGlobalOperator(address)"(
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsLocalOperator(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getIsLocalOperator(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaintenanceMargin(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMaintenanceMargin()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOracleContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOracleContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOraclePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOraclePrice()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getTokenContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradeInfoContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTradeInfoContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradingStartTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTradingStartTime()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasAccountPermissions(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasAccountPermissions(address,address)"(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeV1(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initializeV1(address,address,address,uint256,uint256,string)"(
      token: string,
      oracle: string,
      funder: string,
      maintenanceMargin: BigNumberish,
      initialMargin: BigNumberish,
      marketKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAdmin(address)"(
      admin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeePool(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setFeePool(address)"(
      feePool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFunder(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setFunder(address)"(
      funder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGlobalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setGlobalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInitialMargin(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setInitialMargin(uint256)"(
      initialMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLocalOperator(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setLocalOperator(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaintenanceMargin(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMaintenanceMargin(uint256)"(
      maintenanceMargin: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMarginBank(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMarginBank(address)"(
      marginBank: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOracle(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setOracle(address)"(
      oracle: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTradeInfo(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTradeInfo(address)"(
      tradeInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "startTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopTrading(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "stopTrading()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    trade(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "trade(address[],tuple[])"(
      accounts: string[],
      trades: {
        takerIndex: BigNumberish;
        makerIndex: BigNumberish;
        trader: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFinalSettlement(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawFinalSettlement()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFromPosition(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawFromPosition(address,address,uint256,bytes32)"(
      account: string,
      destination: string,
      amount: BigNumberish,
      memo: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
