/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { DStorage } from "../DStorage";

export class DStorage__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DStorage> {
    return super.deploy(overrides || {}) as Promise<DStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DStorage {
    return super.attach(address) as DStorage;
  }
  connect(signer: Signer): DStorage__factory {
    return super.connect(signer) as DStorage__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DStorage {
    return new Contract(address, _abi, signerOrProvider) as DStorage;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "setAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506100467fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d610333610050602090811b61012717901c565b6001600055610054565b9055565b6101e9806100636000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80636e9960c31461003b578063704b6c0214610059575b600080fd5b610043610079565b604051610050919061015d565b60405180910390f35b61006c61006736600461012f565b6100a9565b6040516100509190610171565b60006100a47fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d610361012b565b905090565b60006100b3610079565b6001600160a01b0316336001600160a01b0316146100ec5760405162461bcd60e51b81526004016100e39061017c565b60405180910390fd5b61011f7fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d61036001600160a01b038416610127565b506001919050565b9055565b5490565b600060208284031215610140578081fd5b81356001600160a01b0381168114610156578182fd5b9392505050565b6001600160a01b0391909116815260200190565b901515815260200190565b6020808252601e908201527f41646d696e61626c653a2063616c6c6572206973206e6f742061646d696e000060408201526060019056fea2646970667358221220673599d51cd8c8a646cd3cbf78b86a3adfd35473638cd7f76773b0d397ff088664736f6c63430007050033";
