/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Operator } from "../Operator";

export class Operator__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Operator> {
    return super.deploy(overrides || {}) as Promise<Operator>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Operator {
    return super.attach(address) as Operator;
  }
  connect(signer: Signer): Operator__factory {
    return super.connect(signer) as Operator__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Operator {
    return new Contract(address, _abi, signerOrProvider) as Operator;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "LogSetLocalOperator",
    type: "event",
  },
  {
    inputs: [],
    name: "getAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "setAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setLocalOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506100467fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d610333610050602090811b6101b517901c565b6001600055610054565b9055565b6102d6806100636000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80636e9960c314610046578063704b6c0214610064578063b4959e7214610084575b600080fd5b61004e610099565b60405161005b919061022f565b60405180910390f35b6100776100723660046101d4565b6100c9565b60405161005b919061025e565b6100976100923660046101f5565b610148565b005b60006100c47fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d61036101b9565b905090565b60006100d3610099565b6001600160a01b0316336001600160a01b03161461010c5760405162461bcd60e51b815260040161010390610269565b60405180910390fd5b61013f7fb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d61036001600160a01b0384166101b5565b5060015b919050565b336000818152600b602090815260408083206001600160a01b038716845290915290819020805460ff1916841515179055517ffe9fa8ad7dbd5e50cbcd1a903ea64717cb80b02e6b737e74f7e2f070b3e4d15f906101a99085908590610243565b60405180910390a25050565b9055565b5490565b80356001600160a01b038116811461014357600080fd5b6000602082840312156101e5578081fd5b6101ee826101bd565b9392505050565b60008060408385031215610207578081fd5b610210836101bd565b915060208301358015158114610224578182fd5b809150509250929050565b6001600160a01b0391909116815260200190565b6001600160a01b039290921682521515602082015260400190565b901515815260200190565b6020808252601e908201527f41646d696e61626c653a2063616c6c6572206973206e6f742061646d696e000060408201526060019056fea264697066735822122014d36f17f2fa851c9605f6aa5fd8a1d254e75cb90639249897cb6d320e81424864736f6c63430007050033";
