on:
  push:
    branches: [main-v2]
  workflow_dispatch:
name: Publish to NPM
jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org
      - run: yarn install --immutable
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
